### ISSUE TITLE
Select custom quality without user intervention

### ISSUE THREAD

**Issue by IcyMint** [elmoiv/redvid#11]
I'm in a situation where I would like to select the highest quality while being under the defined size limit. I can set quality to be highest or lowest but I can't find a way to retrieve the list of qualities from UserSelect or select a custom quality. 
TL;DR: I was wondering if there was a way to select the highest quality under a given size limit, or at least be able to select a quality without needing user intervention.

**Comment by elmoiv** [comment]
Hey @IcyMint ,

From what you said, I understood the following:

* You want redvid to retrieve a list of qualities that you can access within your script instead of user intervention.
* You want a feature that matches the given maximum size to highest possible quality.

Is that all you want, or I missed a thing?

**Comment by IcyMint** [comment]
The second feature would be optimal but if it proves to be too involved the first one would be great. Either one would go a long way to solving the problem.

**Comment by elmoiv** [comment]
Ok.
I will start working on your request ASAP.
Stay tuned :)

**Comment by elmoiv** [comment]
Hey @IcyMint , sorry for adding this feature too late.

`redvid` now can matche the given maximum size to highest possible quality.
To do this:
```python
from redvid import Downloader

reddit = Downloader()
reddit.url = 'https://www.reddit.com/r/Unexpected/comments/9n8mmz/_/'

# redvid will find the quality with the size
# that does not exceed max_s (3 MB)
reddit.max_s = 3 * (1 << 20)

# Enable the "auto match" feature
reddit.auto_max = True

reddit.download()
```

**Comment by IcyMint** [comment]
Just tried it out and it works exactly as expected. Thanks a ton! 🥇
