### ISSUE TITLE
Anyway to download GIFs? Or to auto detect GIFs so can execute another script?

### ISSUE THREAD

**Issue by dermotmcg** [elmoiv/redvid#16]
Hello, not really a bug, more of a question. Fantastic project! Wondering how to download or detect if a link shared is a GIF, as it seems Redvid won't download a GIF. Thanks

**Comment by elmoiv** [comment]
`Redvid` can download gifs that are posted as muted videos.

The main idea behind this project is to mux audio and video as both channels are in separated urls.
It was also to be able to download videos in general.

I will try to see if your feature request can be implemented in the coming update.

Cheers :)
