### ISSUE TITLE
[WinError 2] The system cannot find the file specified: 'av.mp4'  

### ISSUE THREAD

**Issue by shreyasjadhav4** [elmoiv/redvid#17]
Hi, I don't understand why I'm facing this issue while trying to download a video, i get this exception

`[WinError 2] The system cannot find the file specified: 'av.mp4' `

this is my code:
```
reddit = Downloader()
reddit.max = True
reddit.url = str(link)
reddit.download()
```
Any help would be appreciated, thank you so much.

**Comment by elmoiv** [comment]
You don't have `FFmpeg` Installed in your machine.

See issue #12 for help.

**Comment by elmoiv** [comment]
ع
