### ISSUE TITLE
[WinError 5] Access is denied: 'temp'

### ISSUE THREAD

**Issue by shreyasjadhav4** [elmoiv/redvid#19]
```
reddit = Downloader()
reddit.auto_max = True
reddit.path = r'C:\Users\Public\Desktop'
# redvid will find the quality with the size
# that does not exceed max_s (3 MB)
reddit.max_s = 15 * (1 << 20)
reddit.url = link
reddit.download()
```

Error:
```
>> Connecting...
[WinError 5] Access is denied: 'temp'

```

I am trying to download video at my desktop but I am getting this error saying Access is denied. 
May I know how would I resolve this, and how would I set custom name for my video file?

**Comment by elmoiv** [comment]
You must run your script as Administrator or change `reddit.path` to another user instead of **Public** user
