### ISSUE TITLE
Progress bar not easily readable 

### ISSUE THREAD

**Issue by Thomas-Gray** [elmoiv/redvid#21]
Progress bar is not easy to read in the Python shell, needs to be printed on a new line each time. See attached image. I can perhaps attempt to fix, but still fairly bad at programming.

![image](https://user-images.githubusercontent.com/19807095/113522092-e6d02b00-9595-11eb-9411-24cab3786dd6.png)

**Comment by elmoiv** [comment]
Redvid progress bar runs fine on most terminals.
Tested on Windows, MacOS and Linux.

You should use redvid with a a better terminal than Python Shell
