### ISSUE TITLE
Unable to merge the video and audio file in the Temp folder

### ISSUE THREAD

**Issue by sacredsoul98** [elmoiv/redvid#23]
Hi, This is my first issue report ever. So apologies for any mistakes I make. 

I am getting an 'file not found' error when I try to download any video using redvid.

example error I get = ' FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\$github folder\\Dizzibot\\images\\temp\\av.mp4' -> 'E:\\$github folder\\Dizzibot\\images\\a4gyy9ujm7k71-DASH_360.mp4' '

This error is something which i am getting from the last few weeks. It used to work properly before. 

And also I am getting an error saying 'ffmpeg is not recognised as internal or external command' on top of this. 

If you need anything else, glad to help.

![Screenshot 2021-08-29 194036](https://user-images.githubusercontent.com/29597558/131253385-c1773662-2143-478f-a121-c62682213be0.png)

**Comment by elmoiv** [comment]
You don't have `FFmpeg` installed.

I have already included a full guide to install `redvid` requirements here:
https://github.com/elmoiv/redvid#installing-ffmpeg

**Comment by sacredsoul98** [comment]
I have ffmpeg installed. 
![image](https://user-images.githubusercontent.com/29597558/131257040-5c723353-315b-4fc2-bab6-86251136838c.png)

**Comment by elmoiv** [comment]
`ffmpeg is not recognised as internal or external command` means that Windows is not detecting `ffmpeg` binary.

This happens if you had `ffmpeg` incorrectly installed or not set in PATH system environment variable.

**Comment by sacredsoul98** [comment]
Thanks for you explanation. I had the path set wrong.
