### ISSUE TITLE
path should be used before url to work correctly?

### ISSUE THREAD

**Issue by SomaRe** [elmoiv/redvid#25]
First time writing something in github, let me know if I did any mistake. not sure how to change the label to documentation.

I noticed that path should be added before url for it to work as required, it would be great to include anywhere either in documentation or in example code as it doesn't strike immediately to be a problem when dubbing the program when it doesn't save file to given path.

**Comment by elmoiv** [comment]
Can you share the code you used or commands (for console version) with a little more explanation about your issue?

**Comment by elmoiv** [comment]
Closed for inactivity
