### ISSUE TITLE
Download the videos of the top 10 posts from a subreddit

### ISSUE THREAD

**Issue by music-lover99** [elmoiv/redvid#26]
I was wondering how I could download the videos from the top 10 posts of a subreddit.

The program would go through the top posts of a subreddit, if there isn't a video it would skip the post, and if there is a video it would download it.

This is more fit to be put in a "Discussion" heading, but there isn't one, so I thought it'd be alright to put it here.

**Comment by elmoiv** [comment]
I have enabled discussions. Please move your question to it.
