### ISSUE TITLE
Audio is not getting added with the video :(

### ISSUE THREAD

**Issue by Baseerka** [elmoiv/redvid#31]
**Describe the bug**
when I try to download a video it doesn't comes with the audio

Does anyone else have the same problem
I used the code like this
reddit = Downloader()
reddit.path = path
reddit.max = True
reddit.url = url
reddit.download()

**Comment by Baseerka** [comment]
> **Describe the bug** when I try to download a video it doesn't comes with the audio
> 
> Does anyone else have the same problem I used the code like this reddit = Downloader() reddit.path = path reddit.max = True reddit.url = url reddit.download()

Mb vscode doesnot support audio or something :)

**Comment by elmoiv** [comment]
Do you have FFmpeg Installed in your system?

> ## Installing FFmpeg
> ### Windows: 
>
> https://m.wikihow.com/Install-FFmpeg-on-Windows
>
> (*You may need to restart your pc after applying these steps*)
>
> ### Linux: 
>
> `sudo apt install ffmpeg`
>
> ### Mac OS:
>
> * install [Homebrew](https://brew.sh/):
>
>  `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
>
> * Then:
>
>  `$ brew install ffmpeg`

**Comment by 0RaMsY0** [comment]
I have this issue too, the videos are getting downloaded but without the audio even tho i have ffmpeg installed (i am on linux)
