### ISSUE TITLE
[CRITICAL] Reddit changed it's video hosting architecture, can't download video and audio anymore

### ISSUE THREAD

**Issue by Bagdaja** [elmoiv/redvid#32]
**Describe the bug**
Reddit changed it's video hosting architecture, can't download video and audio anymore,      if you set max_q to true it will download just audio as an mp4, if it's not set to anything it will only let you download either a video or an audio file

https://www.reddit.com/r/redditdev/comments/15cdln3/reddit_changed_what_url_audio_from_a_video_is/

**To Reproduce**
Just download any video posted recently

**Expected behavior**
It should detect audio and video qualities separately

I have patched it but very crudely so I didn't make a pull request, Best way to fix it would be by modifying mpdParse I reckon

here is my temporary fix: 

```
def scrape(self):
        """
        Gets direct video and audio (if exists) urls
        """
        self.UNQ = getUNQ(self.page)

        if not self.UNQ:
            Clean(self.temp)
            raise BaseException('No video in this post')
        
        self.r_url = 'https://v.redd.it/' + self.UNQ + '/'

        # Getting Qualities and audio (if exists) from mpd file
        mpd = self.get(
                        self.r_url + 'DASHPlaylist.mpd',
                        _proxies=self.proxies
                        )
        # v1.0.8: Fix new Reddit mechanism
        #VQS, AQS = mpdParse(mpd.text)

        #new fix???
        QS,dontknowwhattodoherelol = mpdParse(mpd.text)
        AQS = [Quality for Quality in QS if 'AUDIO' in Quality[1]]
        VQS = [Quality for Quality in QS if 'AUDIO' not in Quality[1]]
        
        if [VQS, AQS] == [0, 0]:
            raise BaseException('Qualities not found!')

        self.videos = VQS
        
        # Check for Audio
        if AQS:
            self.audio = self.r_url + j(AQS[-1])  #depends on chosen quality, -1 selects the last one (the best)
```

```
def get_and_mux(self):
        """
        Video or muxed video with audio if exists
        """
        self.get_video()

        # v1.0.5: Convert muted videos to be shareable
        if self.audio:
            self.get_audio()
            os.system(
                    'ffmpeg -hide_banner -loglevel panic -y -i "{0}video.mp4"'
                    ' -i "{0}audio.mp4" -vcodec copy -acodec copy "{0}av.mp4"'.format(
                        self.temp
                    )
                )                     #changed audio to mp4 not m4a
        else:
            os.system(
                    'ffmpeg -hide_banner -loglevel panic -y -i "{0}video.mp4"'
                    ' -vcodec copy "{0}av.mp4"'.format(
                        self.temp
                    )
                )

        # Moving video file without using shutil
        os.rename(self.temp + 'av.mp4', self.file_name)

        # Clean Temp folder
        Clean(self.temp)
```

**Comment by navid-sheik** [comment]
Did you resolve it ? I coudn't make it work. It doesn't download the video at all

**Comment by Bagdaja** [comment]
> video

Yes, just go into the Downloader class and replace the functions scrape() and get_and_mux() with the code I provided

**Comment by navid-sheik** [comment]
I don't think it's getting the audio, or at least it tries and then crash because in progress bar you can see it's not downloading the bytes from it

**Comment by mrzpzp** [comment]
Thank you a lot, saved me a lot of trouble. Although, when I first tried your code it gave me:

`FileNotFoundError: [WinError 2] The system cannot find the file specified:`

Tweaking your code a little fixed my problem. **Find this in the redvid.py** 

`def get_audio(self):
        """
        Downloads audio to the current working directory
        """
        self.pgbar(self.log, self.audio, self.temp + 'audio.m4a', '>> Audio:')

    def get_and_mux(self):
        """
        Video or muxed video with audio if exists
        """
        self.get_video()

        # v1.0.5: Convert muted videos to be shareable
        if self.audio:
            self.get_audio()
            os.system(
                    'ffmpeg -hide_banner -loglevel panic -y -i "{0}video.mp4"'
                    ' -i "{0}audio.mp4" -vcodec copy -acodec copy "{0}av.mp4"'.format(
                        self.temp
                    )
                )                     #changed audio to mp4 not m4a
        else:
            os.system(
                    'ffmpeg -hide_banner -loglevel panic -y -i "{0}video.mp4"'
                    ' -vcodec copy "{0}av.mp4"'.format(
                        self.temp
                    )
                )

        # Moving video file without using shutil
        os.rename(self.temp + 'av.mp4', self.file_name)

        # Clean Temp folder
        Clean(self.temp)`


**and change it with the code below. Here it is:** 

`def get_audio(self):
        """
        Downloads audio to the current working directory
        """
        self.pgbar(self.log, self.audio, self.temp + 'av.m4a', '>> Audio:')  # audio.m4a to av.m4a

    def get_and_mux(self):
        """
        Video or muxed video with audio if exists
        """
        self.get_video()

        # v1.0.5: Convert muted videos to be shareable
        if self.audio:
            self.get_audio()
            os.system(
                    'ffmpeg -hide_banner -loglevel panic -y -i "{0}video.mp4"'
                    ' -i "{0}av.m4a" -vcodec copy -acodec copy "{0}av.mp4"'.format(
                        self.temp
                    )
                )                     # changed audio.mp4 to av.m4a
        else:
            os.system(
                    'ffmpeg -hide_banner -loglevel panic -y -i "{0}video.mp4"'
                    ' -vcodec copy "{0}av.mp4"'.format(
                        self.temp
                    )
                )

        # Moving video file without using shutil
        os.rename(self.temp + 'av.mp4', self.file_name)

        # Clean Temp folder
        Clean(self.temp)`

**Comment by vinmorel** [comment]
can we create a PR for this fix?

**Comment by elmoiv** [comment]
I will update it ASAP. Sorry for replying late as I am busy with other projects right now.

**Comment by elmoiv** [comment]
Patched the bug.

Please use `pip install redvid==2.0.0` and inform me if any bugs shows up.
