### ISSUE TITLE
Random audio track given to videos with no audio track

### ISSUE THREAD

**Issue by ChronosNoob** [elmoiv/redvid#35]
**Describe the bug**
A random audio track will be downloaded and applied to silent videos. 
**To Reproduce**
My code is looped through multiple times, I think this may be an issue with the downloader not clearing the cached audio on download/newurl
**Expected behavior**
A silent video to be downloaded.

**Desktop (please complete the following information):**
 - OS: Manjaro

**Comment by elmoiv** [comment]
Please provide me with a snippet of your code to reproduce your issue on my side.

Thank you

**Comment by ChronosNoob** [comment]
I've since fixed the issue by instantiating the downloader each iteration. Here's a code snippet of bugged code, as I don't have the bugged code anymore this is from memory.
`Downloader = Downloader(max_q=True)
for i in range(len(Data)):
   if "v.reddit" in Data[i]:
     downloader.url = Data[i]
     downloader.filename = directory
     downloader.download()
     `
