### ISSUE TITLE
Incorrect URL format - Redvid has suddenly stopped working for me

### ISSUE THREAD

**Issue by kris7ian** [elmoiv/redvid#36]
**Describe the bug**
Since a few days I'm getting a `BaseException: Incorrect URL format` error when trying to download media.

**To Reproduce**

```
from redvid import Downloader

reddit = Downloader(max_q=True)
reddit.url = 'https://v.redd.it/gwfmodtx1p3c1'
reddit.download()
```

Has anything changed on reddits side? I am using redvid==2.0.2

**Comment by kris7ian** [comment]
Looks like my IP was blocked.

**Comment by rohitgr7** [comment]
@kris7ian did you manage to find a solution?

```bash
If you're running a script or application, please register or sign in with your developer credentials <a href=https://www.reddit.com/wiki/api/>here</a>. Additionally make sure your User-Agent is not empty and is something unique and descriptive and try again. if you're supplying an alternate User-Agent string,
try changing back to default as that can sometimes result in a block.
```

this is the error I am getting and I do have api credentials but not sure how to use them while downloading the video.
