### ISSUE TITLE
Sometimes, video is downloaded without audio

### ISSUE THREAD

**Issue by planted101** [elmoiv/redvid#39]
**Describe the bug**
Audio is not present in some videos downloaded. I am unsure if this is similar to other issues, since this happens for every  6-7 videos on my end. I have ffmpeg installed and am currently using macOS. 

**To Reproduce**

    video_path = f"assets/temp/{reddit_id}"
    video_name = f"{name_normalize(reddit_title)[:251]}"
    reddit = Downloader(max_q=True)
    reddit.url = reddit_object["thread_url"]
    reddit.path = video_path
    reddit.filename = video_name
    reddit.download()

    video_full_path = f"{video_path}/{video_name}.mp4"

Videos that were downloaded without audio:
https://www.reddit.com/r/perfectlycutscreams/comments/hgpvd1/playing_uno_with_the_family_be_like/
https://www.reddit.com/r/perfectlycutscreams/comments/e0qiye/student_hides_under_desk_and_grabs_teachers_ankle/

**Expected behavior**
Reddit video saved as an .mp4 with audio

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome(?)

**Additional context**

**Comment by elmoiv** [comment]
Please `pip install redvid --upgrade` and report if any new issues occurred.

Thanks
