### ISSUE TITLE
Output File Named Incorrectly

### ISSUE THREAD

**Issue by SavorSauc3** [elmoiv/redvid#40]
**Description**
After file is scraped from reddit, the file is moved to the output file. It seems that the file isn't named properly, so windows raises a winerror stating that the file could not be found. The error can be fixed by changing the name of the os.rename function in the get_and_mux fuction from "av.mp4" to "video.mp4". I will make a pull request to fix the bug.

**Desktop:**
 - OS: Windows 11

**Comment by elmoiv** [comment]
Do you have `ffmpeg` installed?

because if av.mp4 is not found then you don't have ffmpeg or may not be added to PATH

**Comment by SavorSauc3** [comment]
Oh I see, thanks for letting me know, I am going to close this issue.
