### ISSUE TITLE
Returning the path and file name of the downloaded video?

### ISSUE THREAD

**Issue by MD-Wade** [elmoiv/redvid#6]
Hello! Been using this library for a few days, it's great. I think in 1.05, the download() function would return the entire path to the downloaded file, right? I updated and had to change some stuff around. It'd be really convenient, just a small suggestion.

Thank you,
Wade

**Comment by elmoiv** [comment]
I will update it.

P.S: You can get the path by `.file_name` attribute like this:
```python
from redvid import Downloader

Reddit = Downloader()
Reddit.url = 'bla bla'
Reddit.download()
path = Reddit.file_name
```

**Comment by elmoiv** [comment]
Updated to v1.0.7:
`download()` now returns video path.
